# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField(default=0.0)),
                ('absoluteDeviation', models.FloatField(default=0.0)),
                ('label', models.CharField(max_length=255)),
                ('timeBin', models.DateTimeField()),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ASN')),
            ],
        ),
        migrations.CreateModel(
            name='CongestionRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('timeBin', models.DateTimeField()),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ASN')),
            ],
        ),
        migrations.CreateModel(
            name='Forwarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField(default=0.0)),
                ('absoluteResp', models.FloatField(default=0.0)),
                ('label', models.CharField(max_length=255)),
                ('timeBin', models.DateTimeField()),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ASN')),
            ],
        ),
        migrations.CreateModel(
            name='ForwardingRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('timeBin', models.DateTimeField()),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ASN')),
            ],
        ),
    ]
